### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by MuppudathiVelu** [texei/sfdx-pull-issues#18]
### Request Type
Bug

### Problem Description
I am facing the following issue while importing my records from vs code to salesforce org using texei plugin

>![image](https://github.com/texei/texei-sfdx-plugin/assets/78894466/a29de5dd-73fd-409a-9d6d-bd1f4f34e585)

Sf version: @salesforce/cli/2.16.10 win32-x64 node-v18.18.2

Thanks,
[Muppudathi Velu](https://github.com/MuppudathiVelu)

CC:

**Comment by FabienTaillon** [comment]
Can you give me more details on how to reproduce it ?

**Comment by FabienTaillon** [comment]
Also this is not the correct repository, could you please post your issue with all steps to reproduce here please: https://github.com/texei/texei-sfdx-plugin/issues
